# Generated by Django 6.0.5 on 2026-06-26 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('stage_size', models.PositiveIntegerField(default=20)),
                ('mastery_target', models.PositiveIntegerField(default=80)),
            ],
        ),
        migrations.CreateModel(
            name='LearningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_played', models.DateTimeField(auto_now=True)),
                ('deck', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.deck')),
            ],
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hanzi', models.CharField(max_length=50)),
                ('pinyin', models.CharField(max_length=100)),
                ('meaning', models.CharField(max_length=200)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabularies', to='database.deck')),
            ],
        ),
        migrations.CreateModel(
            name='StageAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.PositiveIntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='database.learningsession')),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.vocabulary')),
            ],
            options={
                'unique_together': {('session', 'vocabulary')},
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery', models.SmallIntegerField(default=0)),
                ('first_try_correct', models.BooleanField(default=False)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('last_review', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='database.learningsession')),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.vocabulary')),
            ],
            options={
                'unique_together': {('session', 'vocabulary')},
            },
        ),
    ]
