# Generated by Django 6.0.6 on 2026-06-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stageassignment',
            index=models.Index(fields=['session', 'stage'], name='database_st_session_740e04_idx'),
        ),
    ]
