# Generated by Django 6.0.5 on 2026-06-29 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_stageassignment_database_st_session_740e04_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='vocabulary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='database.vocabulary'),
        ),
    ]
