# Generated by Django 6.0.5 on 2026-06-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_progress_vocabulary'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsession',
            name='total_stage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
