# Generated by Django 6.0.5 on 2026-06-29 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_learningsession_total_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsession',
            name='last_vocabulary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.vocabulary'),
        ),
    ]
